name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.201
    - name: Setup Xamarin
      uses: maxim-lobanov/setup-xamarin@v1.1
    
    - name: Install tools
      run: dotnet tool restore
    - name: Install dependencies
      run: dotnet paket restore
    - name: Build
      run: dotnet paketdotnet publish ./FBlazorShop.Web/FBlazorShop.Web.fsproj /p:Configuration=Release /p:Platform=x64 restore

cd ./FBlazorShop.Web/bin/x64/Release/netcoreapp3.1/publish/
